// angular/src/app/message/message.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { Message } from '../app.component';

@Component({
  selector: 'app-message',
  templateUrl: './message.component.html',
  styleUrls: ['./message.component.css']
})
export class MessageComponent implements OnInit {

  @Input() message: any;

  ngOnInit(): void {

  }

}

<div class="elem">
    <span class="message">{{message.message}}</span>
    <span class="date">{{message.date.toString()}}</span>
  </div>

// qwik/src/routes/components/MessageComponent.tsx
import { component$ } from '@builder.io/qwik';
import './MessageComponent.css';
import type { Message } from '..';

export default component$((props: {message: Message}) => {
    return <div class="elem">
        <span class="message">{props.message.message}</span>
        <span class="date">{props.message.date.toString()}</span>
    </div>;
});
