// react-app/src/components/MessageComponent.tsx
import { useState } from 'react';
import logo from './logo.svg';
import './MessageComponent.css';

function MessageComponent(props: any) {
    return <div className="elem">
        <span className="message">{props.message.message}</span>
        <span className="date">{props.message.date.toString()}</span>
    </div>;
};

export default MessageComponent;
function componentDidMount(arg0: () => void) {
    throw new Error('Function not implemented.');
}

// qwik/src/routes/components/MessageComponent.tsx
import { component$ } from '@builder.io/qwik';
import './MessageComponent.css';
import type { Message } from '..';

export default component$((props: {message: Message}) => {
    return <div class="elem">
        <span class="message">{props.message.message}</span>
        <span class="date">{props.message.date.toString()}</span>
    </div>;
});
