// angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { OnChange } from 'property-watch-decorator';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {

  title: string = "Angular app";
  LS: string = "jsFrameworkComparison-angular-messages";

  @OnChange((value, _) => console.log('new value for count: ' + value))
  count: number = 0;

  list: Message[] = [];

  ngOnInit() {
    setInterval(() => {
      this.count++;
      console.log
    }, 1000);

    this.list = JSON.parse(window.localStorage.getItem(this.LS) ?? "[]") as Message[];
  }

  sendMessage(event: any) {
    this.list.push({ message: event.target.value, date: new Date() });
    window.localStorage.setItem(this.LS, JSON.stringify(this.list));
  }

  emptyList() {
    this.list = [];
    window.localStorage.setItem(this.LS, "[]");
  }
}


export type Message = {
  message: string;
  date: Date;
};
<div class="App">
  <header class="header">
    <h1>{{title}}</h1>
    <img src="./assets/icon.svg" class="logo" alt="logo" />
    <span>{{count}}</span>
  </header>
  <div class="content">
    <input type="text" (change)="sendMessage($event)" />
    <app-message *ngFor="let elem of list" [message]="elem"></app-message>
    <button (click)="emptyList()">Empty</button>
  </div>
</div>

// solid/src/App.tsx
import { Component, createEffect, createSignal, onCleanup } from 'solid-js';

import logo from './logo.svg';
import styles from './App.module.css';
import MessageComponent from './components/MessageComponent';

const App: Component = () => {

  const title: string = 'Solid app';
  const LS: string = 'jsFrameworkComparison-solid-messages';

  const [count, setCount] = createSignal<number>(0);
  let interval = setInterval(() => { setCount(count() + 1) }, 1000);
  onCleanup(() => clearInterval(interval));

  createEffect(() => console.log('new value for count: ' + count()));

  const [list, setList] = createSignal<Message[]>([]);

  setList(JSON.parse(window.localStorage.getItem(LS) ?? '[]') as Message[]);

  const sendMessage = (event: any) => {
    setList([...list(), { message: event.target.value, date: new Date() }]);
    window.localStorage.setItem(LS, JSON.stringify(list()));
  }

  const emptyList = () => {
    setList([]);
    window.localStorage.setItem(LS, '[]');
  }

  return (
    <div class={styles.App}>
      <header class={styles.header}>
        <h1>{title}</h1>
        <img src={logo} class={styles.logo} alt="logo" />
        <span>{count()}</span>
      </header>
      <div class={styles.content}>
        <input type="text" onchange={(event) => sendMessage(event)} />
        {list().map(elem => <MessageComponent message={elem} />)}
        <button onclick={() => emptyList()}>Empty</button>
      </div>
    </div>
  );
};

export type Message = {
  message: string;
  date: Date;
}

export default App;
